/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

/**
 *
 * @author sala303b
 */
public class FormeMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormeMenuPrincipal
     */
    public FormeMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraDeMenu = new javax.swing.JMenuBar();
        mnCadastrar = new javax.swing.JMenu();
        mniCadProduto = new javax.swing.JMenuItem();
        mniCadCategoria = new javax.swing.JMenuItem();
        mnListar = new javax.swing.JMenu();
        mniLisProduto = new javax.swing.JMenuItem();
        mniLisCategoria = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BarraDeMenu.setToolTipText("");

        mnCadastrar.setText("Cadastrar");

        mniCadProduto.setText("Cadastrar Produto");
        mniCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadProdutoActionPerformed(evt);
            }
        });
        mnCadastrar.add(mniCadProduto);

        mniCadCategoria.setText("Cadastrar Categoria");
        mniCadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadCategoriaActionPerformed(evt);
            }
        });
        mnCadastrar.add(mniCadCategoria);

        BarraDeMenu.add(mnCadastrar);

        mnListar.setText("Listar");

        mniLisProduto.setText("Listar Produtos");
        mniLisProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLisProdutoActionPerformed(evt);
            }
        });
        mnListar.add(mniLisProduto);

        mniLisCategoria.setText("Listar Categoria");
        mniLisCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLisCategoriaActionPerformed(evt);
            }
        });
        mnListar.add(mniLisCategoria);

        BarraDeMenu.add(mnListar);

        mnSair.setText("Sair");
        BarraDeMenu.add(mnSair);

        setJMenuBar(BarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadProdutoActionPerformed
        // TODO add your handling code here:
        FormeCadProduto form = new FormeCadProduto();
        form.setVisible(true);
        
    }//GEN-LAST:event_mniCadProdutoActionPerformed

    private void mniCadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadCategoriaActionPerformed
        // TODO add your handling code here:
        FormCadCategoria form = new FormCadCategoria();
        form.setVisible(true);
    }//GEN-LAST:event_mniCadCategoriaActionPerformed

    private void mniLisCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLisCategoriaActionPerformed
        // TODO add your handling code here:
        FormListCategoria form = new FormListCategoria();
        form.setVisible(true);
    }//GEN-LAST:event_mniLisCategoriaActionPerformed

    private void mniLisProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLisProdutoActionPerformed
        // TODO add your handling code here:
         FormListProduto form = new FormListProduto();
        form.setVisible(true);
    }//GEN-LAST:event_mniLisProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormeMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormeMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormeMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormeMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormeMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraDeMenu;
    private javax.swing.JMenu mnCadastrar;
    private javax.swing.JMenu mnListar;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenuItem mniCadCategoria;
    private javax.swing.JMenuItem mniCadProduto;
    private javax.swing.JMenuItem mniLisCategoria;
    private javax.swing.JMenuItem mniLisProduto;
    // End of variables declaration//GEN-END:variables
}
